
@startuml

rectangle client as "UI Client(s)"{
    component website
    component mobileApp
}

rectangle aboveStore as "Above Store" {
    node storeProfile as "Store Profile"
    node storeService as "Store Service"
}

storeService -> storeProfile
client --> storeService
@enduml